version: '3'
services:
  elasticsearch:
    image: elasticsearch:8.12.0
    volumes:
      - ./esdata:/usr/share/elasticsearch/data
    ports:
      - 9200:9200
      - 9300:9300
    environment:
      - discovery.type=single-node
      - xpack.security.enabled=false
      - node.name=elastic
      - cluter.name = es-docker-cluster
    networks:
      - elastic

  kibana:
    image: kibana:8.12.0
    container_name: kibana
    environment:
      - node.name=kibana
      - cluster.name = es-docker-cluster
      - ELASTICSEATCH_HOSTS = http://elasticsearch:9200
    ports:
      - 5601:5601
    depends_on:
      - elasticsearch
    networks:
      - elastic

  grafana:
    image: grafana/grafana:latest
    container_name: grafana
    ports:
      - "3000:3000"
    networks:
      - elastic

volumes:
  esdata:

networks:
  elastic:
    driver: bridge  
